<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!DOCTYPE DreamTravel [
        <!ELEMENT DreamTravel (Customer, Tours)>
        <!ELEMENT Customer (Name, Email, Address, Discount)>
        <!ELEMENT Name (#PCDATA)>
        <!ELEMENT Email (#PCDATA)>
        <!ELEMENT Address (#PCDATA)>
        <!ELEMENT Discount (#PCDATA)>
        <!ELEMENT Tours (Tour)+>
        <!ELEMENT Tour (Country, City, Hotel, URL, Date, Days, Price, Type, Option+)>
        <!ELEMENT Country (#PCDATA)>
        <!ELEMENT City (#PCDATA)>
        <!ELEMENT Hotel (#PCDATA)>
        <!ELEMENT URL (#PCDATA)>
        <!ELEMENT Date (#PCDATA)>
        <!ELEMENT Days (#PCDATA)>
        <!ELEMENT Price (#PCDATA)>
        <!ELEMENT Type (#PCDATA)>
        <!ELEMENT Option (#PCDATA)>
        ]>
<DreamTravel>
    <Customer>
        <Name>Ivanov Ivan</Name>
        <Email>ivanov@mail.ru</Email>
        <Address>Minsk, Masherov Avenue, 14/47</Address>
        <Discount>0</Discount>
    </Customer>
    <Tours>
        <Tour>
            <Country>Spain</Country>
            <City>Barcelona</City>
            <Hotel>El Palace Hotel</Hotel>
            <URL>https://www.hotelpalacebarcelona.com/en/</URL>
            <Date>10.07.2016</Date>
            <Days>10</Days>
            <Price>1300</Price>
            <Type>Hot Tour</Type>
            <Option>Flight</Option>
            <Option>Medical insurance</Option>
        </Tour>
        <Tour>
            <Country>Georgia</Country>
            <City>Batumi</City>
            <Hotel>Sheraton Batumi Hotel</Hotel>
            <URL>http://www.sheratonbatumi.com/</URL>
            <Date>30.07.2016</Date>
            <Days>14</Days>
            <Price>2000</Price>
            <Type>Classic</Type>
            <Option>Flight</Option>
            <Option>Medical insurance</Option>
        </Tour>
    </Tours>
</DreamTravel>