<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!DOCTYPE Airport [
        <!ELEMENT Airport (Administrator, Flight, Dispatcher, BrigadeList)>
        <!ELEMENT Administrator (#PCDATA)>
        <!ELEMENT Flight (#PCDATA)>
        <!ELEMENT Dispatcher (#PCDATA)>
        <!ELEMENT BrigadeList (Brigade)+>
        <!ELEMENT Brigade (Pilot, Navigator, Stewardess)>
        <!ELEMENT Pilot (#PCDATA)>
        <!ELEMENT Navigator (#PCDATA)>
        <!ELEMENT Stewardess (#PCDATA)>
        ]>
<Airport>
    <Administrator>Ivanov</Administrator>
    <Flight>Minsk-London</Flight>
    <Dispatcher>Sokolov</Dispatcher>
    <BrigadeList>
        <Brigade>
            <Pilot>Petrov</Pilot>
            <Navigator>Newman</Navigator>
            <Stewardess>Kent</Stewardess>
        </Brigade>
        <Brigade>
            <Pilot>Sidorov</Pilot>
            <Navigator>Miller</Navigator>
            <Stewardess>Johns</Stewardess>
        </Brigade>
        <Brigade>
            <Pilot>Sidorov</Pilot>
            <Navigator>Miller</Navigator>
            <Stewardess>Johns</Stewardess>
        </Brigade>
    </BrigadeList>
</Airport>