=== AlenaDrachova/JD2016/src/by/it/luksha/jd03_02/xml/cars.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified"
           elementFormDefault="qualified"
           targetNamespace="http://luksha.it-academy.by/xml/cars"
           xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="cars">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="car" maxOccurs="unbounded" minOccurs="0">
          <xs:complexType>
            <xs:sequence>
              <xs:element type="xs:int" name="ID"/>
              <xs:element type="xs:string" name="Brand"/>
              <xs:element type="xs:string" name="Model"/>
              <xs:element type="xs:string" name="Category"/>
              <xs:element type="xs:int" name="Cost"/>
              <xs:element type="xs:double" name="Consumption"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== AlenaDrachova/JD2016/src/by/it/luksha/jd03_02/xml/cars.xml
<?xml version="1.0" encoding="UTF-8"?>
<cars
        xmlns="http://luksha.it-academy.by/xml/cars"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://luksha.it-academy.by/xml/cars cars.xsd">
    <car>
        <ID>1</ID>
        <Brand>Toyota</Brand>
        <Model>LC 200</Model>
        <Category>off-road</Category>
        <Cost>120</Cost>
        <Consumption>15.7</Consumption>
    </car>
    <car>
        <ID>2</ID>
        <Brand>Honda</Brand>
        <Model>Civic 5D</Model>
        <Category>economy</Category>
        <Cost>35</Cost>
        <Consumption>5.5</Consumption>
    </car>
    <car>
        <ID>3</ID>
        <Brand>BMW</Brand>
        <Model>7er</Model>
        <Category>business</Category>
        <Cost>70</Cost>
        <Consumption>12.5</Consumption>
    </car>
</cars>
