=== AlenaDrachova/JD2016/src/by/it/luksha/jd03_02/xml/orders.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified"
           elementFormDefault="qualified"
           targetNamespace="http://luksha.it-academy.by/xml/orders"
           xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="orders">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="order">
          <xs:complexType>
            <xs:sequence>
              <xs:element type="xs:int" name="ID"/>
              <xs:element type="xs:int" name="FK_User"/>
              <xs:element type="xs:int" name="FK_Car"/>
              <xs:element type="xs:time" name="StartRent"/>
              <xs:element type="xs:time" name="EndRent"/>
              <xs:element type="xs:int" name="TotalCost"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== AlenaDrachova/JD2016/src/by/it/luksha/jd03_02/xml/orders.xml
<?xml version="1.0" encoding="UTF-8"?>
<orders
        xmlns="http://luksha.it-academy.by/xml/orders"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://luksha.it-academy.by/xml/orders orders.xsd">
    <order>
        <ID>1</ID>
        <FK_User>1</FK_User>
        <FK_Car>1</FK_Car>
        <StartRent>2016-06-29 22:00:01</StartRent>
        <EndRent>2016-06-30 22:00:01</EndRent>
        <TotalCost>120</TotalCost>
    </order>
</orders>
