=== AlenaDrachova/JD2016/src/by/it/luksha/jd03_02/xml/users.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified"
           elementFormDefault="qualified"
           targetNamespace="http://luksha.it-academy.by/xml/users"
           xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="users">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="user" maxOccurs="unbounded" minOccurs="0">
          <xs:complexType>
            <xs:sequence>
              <xs:element type="xs:int" name="ID"/>
              <xs:element type="xs:string" name="Login"/>
              <xs:element type="xs:string" name="Password"/>
              <xs:element type="xs:string" name="Email"/>
              <xs:element type="xs:int" name="FK_Role"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== AlenaDrachova/JD2016/src/by/it/luksha/jd03_02/xml/users.xml
<?xml version="1.0" encoding="UTF-8"?>
<users
        xmlns="http://luksha.it-academy.by/xml/users"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://luksha.it-academy.by/xml/users users.xsd">
    <user>
        <ID>1</ID>
        <Login>Toyota</Login>
        <Password>LC 200</Password>
        <Email>off-road</Email>
        <FK_Role>120</FK_Role>
    </user>
    <user>
        <ID>1</ID>
        <Login>Toyota</Login>
        <Password>LC 200</Password>
        <Email>off-road</Email>
        <FK_Role>120</FK_Role>
    </user>
    <user>
        <ID>1</ID>
        <Login>Toyota</Login>
        <Password>LC 200</Password>
        <Email>off-road</Email>
        <FK_Role>120</FK_Role>
    </user>
</users>
