=== AlenaDrachova/JD2016/src/by/it/sergeev/jd02_07/catalog.dtd
<?xml version="1.0" encoding="UTF-8" ?>
        <!ELEMENT Catalog (section+)>
        <!ELEMENT section (product+)>
        <!ATTLIST section
                name CDATA #REQUIRED>
        <!ELEMENT product (description)>
        <!ATTLIST product
                manufacturer CDATA #REQUIRED
                name CDATA #REQUIRED
                model CDATA #REQUIRED
                price CDATA #REQUIRED>
        <!ELEMENT description (#PCDATA)>

=== AlenaDrachova/JD2016/src/by/it/sergeev/jd02_07/catalog.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Catalog SYSTEM "Catalog.dtd" >
<!-- Все данные по каталогу взяты с сайта onliner.by 1 июля 2016 года -->
<Catalog>
    <section name="notebooks">
        <product manufacturer="Apple" name="Macbook Pro 15" model="MJLT2" price="4799,00">
            <description>15.4" 2880 x 1800 глянцевый, Intel Core i7 2500 МГц, 16 ГБ, 512 Гб (SSD), AMD Radeon R9 M370X, OS X, цвет корпуса серебристый</description>
        </product>
        <product manufacturer="Samsung" name="Samsung ATIV" model="NP905S3G-K02RU" price="1538,88">
            <description>13.3" 1366 x 768 матовый, AMD A6 1450 1000 МГц, 4 ГБ, 128 Гб (SSD), AMD Radeon HD 8250, Windows 8, цвет корпуса белый</description>
        </product>
        <product manufacturer="Lenovo" name="Lenovo ThinkPad P70" model="20ER0029RT" price=" 8319,78">
            <description>17.3" 1920 x 1080, Intel Xeon E3-1505M v5 2800 МГц, 16 ГБ, 1000 ГБ + 256 Гб (HDD + SSD), NVIDIA Quadro M3000M, цвет корпуса черный</description>
        </product>
    </section>
    <section name="phones">
        <product manufacturer="Apple" name="iPhone 6s Plus" model="128GB" price="2200,00">
            <description>Apple iOS, экран 5.5" IPS (1080x1920), ОЗУ 2 ГБ, флэш-память 128 ГБ, камера 12 Мп, цвет розовый</description>
        </product>
        <product manufacturer="Samsung" name="Galaxy Note 5" model="128GB" price="2000,00">
            <description>Android, экран 5.7" AMOLED (1440x2560), ОЗУ 4 ГБ, флэш-память 128 ГБ, камера 16 Мп, аккумулятор 3000 мАч, цвет розовый</description>
        </product>
        <product manufacturer="Lenovo" name="Vibe X3 Matte White" model="32GB" price="1029,00">
            <description>Android, экран 5.5" IPS (1080x1920), ОЗУ 3 ГБ, флэш-память 32 ГБ, карты памяти, камера 21 Мп, аккумулятор 3600 мАч, Dual SIM, цвет белый </description>
        </product>
    </section>
    <section name="tablets">
        <product manufacturer="Apple" name="iPad Pro 256GB Gold" model="256GB" price="3103,96 р.">
            <description>12.9" IPS (2732x2048), iOS, ОЗУ 4 ГБ, флэш-память 256 ГБ, цвет золотистый</description>
        </product>
        <product manufacturer="Samsung" name="Galaxy View 32GB LTE Black" model="32GB" price="2069,79">
            <description>18.4" (1920x1080), Android, ОЗУ 2 ГБ, флэш-память 32 ГБ, LTE, цвет черный</description>
        </product>
        <product manufacturer="Lenovo" name="ThinkPad 10 128GB LTE" model="128GB" price="1921,07">
            <description>10.1" IPS (1920x1200), Windows 10, ОЗУ 4 ГБ, флэш-память 128 ГБ, LTE, цвет черный</description>
        </product>
    </section>
</Catalog>
