=== AlenaDrachova/JD2016/src/by/it/novik/jd02_07/payments/payments.dtd
<?xml version="1.0" encoding="UTF-8" ?>
        <!ELEMENT Users (User)+>
        <!ELEMENT User (ID, First_Name, Middle_Name, Last_Name, Passport,
                Address, Phone, Email, Nickname, Password, Role, Accounts*)>
        <!ELEMENT ID (#PCDATA)>
        <!ELEMENT First_Name (#PCDATA)>
        <!ELEMENT Middle_Name (#PCDATA)>
        <!ELEMENT Last_Name (#PCDATA)>
        <!ELEMENT Passport (#PCDATA)>
        <!ELEMENT Address (#PCDATA)>
        <!ELEMENT Phone (#PCDATA)>
        <!ELEMENT Email (#PCDATA)>
        <!ELEMENT Nickname (#PCDATA)>
        <!ELEMENT Password (#PCDATA)>
        <!ELEMENT Role (#PCDATA)>
        <!ELEMENT Accounts (account)*>
        <!ELEMENT account (Number,Amount,State,Payments*)>
        <!ELEMENT Number (#PCDATA)>
        <!ELEMENT Amount (#PCDATA)>
        <!ELEMENT State (#PCDATA)>
        <!ELEMENT Payments (payment)*>
        <!ELEMENT payment (ID_p,Source,Description,Destination,Date,Amount_p)>
        <!ELEMENT ID_p (#PCDATA)>
        <!ELEMENT Source (#PCDATA)>
        <!ELEMENT Description (#PCDATA)>
        <!ELEMENT Destination (#PCDATA)>
        <!ELEMENT Date (#PCDATA)>
        <!ELEMENT Amount_p (#PCDATA)>

=== AlenaDrachova/JD2016/src/by/it/novik/jd02_07/payments/payments.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Users SYSTEM "payments.dtd" >
<Users>
    <User>
        <ID>
            1
        </ID>
        <First_Name>
            Иван
        </First_Name>
        <Middle_Name>
            Иванович
        </Middle_Name>
        <Last_Name>
            Иванов
        </Last_Name>
        <Passport>
            MC241234, 21.02.2015
        </Passport>
        <Address>
            г.Минск, ул. Глебки, 5-15
        </Address>
        <Phone>
            +375447512345
        </Phone>
        <Email>
            ivanov@mail.ru
        </Email>
        <Nickname>
            iv_ivan
        </Nickname>
        <Password>
            zaq1@WSX
        </Password>
        <Role>
            Client
        </Role>
        <Accounts>
        <account>
            <Number>
                10123456
            </Number>
            <Amount>
                235
            </Amount>
            <State>
                не блокирован
            </State>
            <Payments>
            <payment>
                <ID_p>
                    2345
                </ID_p>
                <Source>
                    23456789
                </Source>
                <Description>
                    Оплата за воду
                </Description>
                <Destination>
                    231456789
                </Destination>
                <Date>
                    25.06.2016
                </Date>
                <Amount_p>
                    20
                </Amount_p>
            </payment>
            </Payments>
        </account>
        </Accounts>
    </User>
    <User>
    <ID>
        45
    </ID>
    <First_Name>
        Петр
    </First_Name>
    <Middle_Name>
        Иванович
    </Middle_Name>
    <Last_Name>
        Зеленков
    </Last_Name>
    <Passport>
        MC256678, 02.04.2015
    </Passport>
    <Address>
        г.Минск, ул. Шаранговича, 4-15
    </Address>
    <Phone>
        +375296753427
    </Phone>
    <Email>
        zelenkov@mail.ru
    </Email>
    <Nickname>
        p_zelenkov
    </Nickname>
    <Password>
        cde3$RRV
    </Password>
    <Role>
        Admin
    </Role>
    </User>
</Users>
