=== AlenaDrachova/JD2016/src/by/it/belsky/jd02_07/WebSite/Users.dtd
<?xml version="1.0" encoding="UTF-8"?>
        <!ELEMENT Users (User)+>
        <!ELEMENT User (Email, Password, Nickname, Packages) >
        <!ELEMENT Email (#PCDATA) >
        <!ELEMENT Password (#PCDATA) >
        <!ELEMENT Nickname (#PCDATA) >
        <!ELEMENT Packages (Package)+ >
        <!ELEMENT Package (Drawing, Assembly, Specification, Literature, Scheme) >
        <!ELEMENT Drawing (#PCDATA) >
        <!ELEMENT Assembly (#PCDATA) >
        <!ELEMENT Specification (#PCDATA) >
        <!ELEMENT Literature (#PCDATA) >
        <!ELEMENT Scheme (#PCDATA) >

=== AlenaDrachova/JD2016/src/by/it/belsky/jd02_07/WebSite/Users.xml
<?xml version ="1.0" encoding="UTF-8" ?>
<!DOCTYPE Users SYSTEM "Users.dtd" >
<Users>
    <User>
        <Email>
            Mina_2@mail.ru
        </Email>
        <Password>
            10VENERA01
        </Password>
        <Nickname>
            Leopard
        </Nickname>
        <Packages>
            <Package>
                <Drawing>
                    gear
                </Drawing>
                <Assembly>
                    reducer
                </Assembly>
                <Specification>
                    reducer specification
                </Specification>
                <Literature>
                    machine tools
                </Literature>
                <Scheme>
                    kinematic scheme
                </Scheme>
            </Package>
            <Package>
                <Drawing>
                    bearing
                </Drawing>
                <Assembly>
                    gearbox
                </Assembly>
                <Specification>
                    gearbox specification
                </Specification>
                <Literature>
                    ISO documents
                </Literature>
                <Scheme>
                    hydraulic scheme
                </Scheme>
            </Package>
        </Packages>
    </User>
</Users>
